version: "2"

services:
    web:
        ports:
            - "80:5000"
        tty: true
        stdin_open: true
        command: debug
        volumes:
            - ./web/mastermind:/home/web/mastermind
            - ./web/tests:/home/web/tests
