version: "2"

services:
    web:
        ports:
            - "5000:5000"
        tty: true
        stdin_open: true
        command: debug
        volumes:
            - ./web/mastermind:/home/web/mastermind:ro
            - ./web/tests:/home/web/tests:ro
