version: "2"

services:
    web:
        build:
            dockerfile: build/web/Dockerfile
            context: .
        env_file:
            - deploy/web/env
        volumes:
            - db:/home/web/instance
        command: run

volumes:
    db:
        driver: local
