version: "2"

services:
    web:
        container_name: rest_test_web
        build:
            dockerfile: build/web/Dockerfile
            context: .
        env_file:
            - deploy/env
            - deploy/web/env
        volumes:
            - db:/home/web/instance

    web_server:
        container_name: rest_test_web_server
        build:
            dockerfile: build/web_server/Dockerfile
            context: .
        env_file:
            - deploy/env
            - deploy/web_server/env
        ports:
            - "80:80"
        depends_on:
            - web

volumes:
    db:
        driver: local
